# fly.toml app configuration file generated for mgporter-battleship-online on 2023-11-15T11:46:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mgporter-battleship-online"
primary_region = "iad"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
