package io.mgporter.battleship_online.models;

public enum MessageType {
  CREDENTIALS, JOINLOBBY, JOINGAME, EXITEDLOBBY, EXITEDGAME, GAMEREMOVED, CREATEDGAME,
  REJECTEDJOIN_ALREADY_IN_GAME, REJECTEDJOIN_NO_OBSERVERS, ACCEPTEDJOIN
}
