package io.mgporter.battleship_online.enums;

public enum MessageType {
  CREDENTIALS, GAMEROOMLIST, JOINLOBBY, JOINGAME, EXITEDLOBBY, EXITEDGAME, GAMEREMOVED, CREATEDGAME,
  REJECTEDJOIN_ALREADY_IN_GAME, REJECTEDJOIN_NO_OBSERVERS, REJECTEDJOIN_ROOM_FULL, REJECTEDJOIN_GAME_NOT_FOUND,
  ACCEPTEDJOIN, MAXGAMEROOMSREACHED, SAVEDATA
}
