package io.mgporter.battleship_online.enums;

public enum PacketType {
  ATTACK, ATTACK_MISSED, ATTACK_HITSHIP, ATTACK_SUNKSHIP, ATTACK_ALLSUNK, SUNKSHIP_INFO,
  PLACED_SHIP, PLACED_COMPLETE,
  M, H, S,            // Short for Missed, Hit, Sunk
  GAME_INITIALIZED, GAME_START, GAME_ATTACK_PHASE_START, GAME_WAITING_FOR_PLAYERS,
  PLAYERLIST_UPDATE, LOAD_ALL_DATA, ERROR

}